import type { ComponentType } from "react";
import type { SceneProps } from "../recipeSchema";

/**
 * Scene registry — REGENERATED by scaffold_reel when the recipe uses custom
 * scenes. Each entry maps a segment's `scene` name to the component in this
 * directory that renders it. Hand-add entries here if you write scenes after
 * scaffolding.
 */
export const scenes: Record<string, ComponentType<SceneProps>> = {};
